apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: test
  source:
    path: dev
    repoURL: https://github.com/ClownandBox/argocd-lab.git
    targetRevision: HEAD
