apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: gcr.io/heptio-images/ks-guestbook-demo:~0.1
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default  # Replace with your desired ArgoCD project
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD  # Replace with the target revision (commit, tag, or branch)
    path: guestbook
    plugin:
      name: my-plugin-v1.0
      env:
        - name: SERVICE
          value: my-service
  destination:
    server: https://kubernetes.default.svc  # Replace with your Kubernetes cluster API URL
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      # - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
