apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: diff
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
          name: guestbook-ui
          ports:
            - containerPort: 80
          env:
            - name: ENV_VAR_1
              value: value1
            - name: ENV_VAR_3
              value: value1
            # - name: ENV_VAR_3
            #   value: value1
