apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: guestbook-ui
    #solutionId: test
