apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
#  namespace: guestbook
spec:
  replicas: 1
  revisionHistoryLimit:
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: guestbook-ui
          ports:
            - containerPort: 80
          env:
            - name: ENV_VAR_22
              value: value2
            - name: ENV_VAR_19
              value: value2
