apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: test_slack_plugin
    argocd.argoproj.io/manifest-generate-paths: .
  name: gb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cf  # Replace with your desired ArgoCD project
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD  # Replace with the target revision (commit, tag, or branch)
    path: guestbook
  destination:
    server: https://kubernetes.default.svc # Replace with your Kubernetes cluster API URL
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
