apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/pasha-codefresh/precisely-gitsource.git'
        targetRevision: HEAD
        paths:
          - apps/guestbook
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: "{{name}}"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/pasha-codefresh/precisely-gitsource.git'
        path: "{{name}}"
        targetRevision: HEAD
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
