apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        repoURL: 'https://github.com/pasha-codefresh/precisely-gitsource.git'
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{.path.basename}}'
      labels:
        app.kubernetes.io/instance: "{{.path.basename}}"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/pasha-codefresh/precisely-gitsource.git'
        path: "{{.path.path}}"
        targetRevision: HEAD
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
