apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/pasha-codefresh/precisely-gitsource.git'
        revision: HEAD
        directories:
          - path: apps/**
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: "{{.path.path}}"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/pasha-codefresh/precisely-gitsource.git'
        path: "{{.path.path}}"
        targetRevision: HEAD
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
