apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: excluded-resource
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default  # Replace with your desired ArgoCD project
  source:
    repoURL: https://github.com/pasha-codefresh/precisely-gitsource
    targetRevision: main  # Replace with the target revision (commit, tag, or branch)
    path: ./helm-apps/helm-guestbook
    helm:
      releaseName: gb
  destination:
    server: https://kubernetes.default.svc  # Replace with your Kubernetes cluster API URL
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      # - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
