apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app
  namespace: codefresh
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .; ../kustomize-resources
    argocd-image-updater.argoproj.io/image-list: gcr.io/heptio-images/ks-guestbook-demo:^0.1
spec:
  project: default  # Replace with your desired ArgoCD project
  source:
    repoURL: https://github.com/pasha-codefresh/precisely-gitsource
    targetRevision: HEAD  # Replace with the target revision (commit, tag, or branch)
    path: ./kustomize
    kustomize:
      patches:
        - target:
            kind: Deployment
            name: guestbook-ui
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/ports/0/containerPort
              value: 443
  destination:
    server: https://kubernetes.default.svc  # Replace with your Kubernetes cluster API URL
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      # - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
