apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app
  namespace: codefresh
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .; ../kustomize-resources
spec:
  project: default  # Replace with your desired ArgoCD project
  source:
    repoURL: https://github.com/pasha-codefresh/precisely-gitsource
    targetRevision: HEAD  # Replace with the target revision (commit, tag, or branch)
    path: ./kustomize
  destination:
    server: https://kubernetes.default.svc  # Replace with your Kubernetes cluster API URL
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      # - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
