apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification
  namespace: cf-argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
spec:
  project: cf  # Replace with your desired ArgoCD project
  source:
    repoURL: https://github.com/pasha-codefresh/precisely-gitsource
    targetRevision: HEAD  # Replace with the target revision (commit, tag, or branch)
    path: ./slack
  destination:
    server: https://kubernetes.default.svc  # Replace with your Kubernetes cluster API URL
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
