apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - list:
        elements:
          - cluster: engineering-dev
            url: https://kubernetes.default.svc
            env: env-dev
            path: apps/guestbook
            ns: guestbook
          - cluster: engineering-qa
            url: https://kubernetes.default.svc
            env: env-qa
            path: apps/guestbook2
            ns: guestbook2
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: envLabel
              operator: In
              values:
                - env-dev
          maxUpdate: 50%  # if undefined, all applications matched are updated together (default is 100%)
        - matchExpressions:
            - key: envLabel
              operator: In
              values:
                - env-qa
          maxUpdate: 50%      # if 0, no matched applications will be updated
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: '{{.cluster}}-guestbook'
      labels:
        envLabel: '{{.env}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/pasha-codefresh/precisely-gitsource.git'
        targetRevision: HEAD
        path: {{ .path }}
      destination:
        server: '{{.url}}'
        namespace: '{{.ns}}'
