apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  # Teams Workflows service configuration
  service.teams-workflows: |
    recipientUrls:
      channelName: $channel-workflows-url

  # Templates with teams-workflows support
  template.app-sync-succeeded: |
    teams-workflows:
      facts: |
        [{
          "name": "Sync Status",
          "value": "{{.app.status.sync.status}}"
        },{
          "name": "Synced at",
          "value": "{{.app.status.operationState.finishedAt}}"
        },{
          "name": "Repository",
          "value": "{{.app.spec.source.repoURL}}"
        }]
      themeColor: '#000080'
      title: Application {{.app.metadata.name}} has been successfully synced
      text: Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.
      summary: "{{.app.metadata.name}} sync succeeded"